version: '3.1'

services:

  db:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_PASSWORD: chatsexeverywhere
      POSTGRES_DB: chat-sex

    ports:
      - 5432:5432

  db-test:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_PASSWORD: chatsexeverywhere
      POSTGRES_DB: chat-sex-test

    ports:
      - 5439:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
